### PR TITLE
ERS-478 fix testdata load

### PR DESCRIPTION
**Pull request by psjobergprivat**
Loading testdata broke after bumping Liquibase since handling of "NULL" in csv file changed:

ORGANISATION_T.**csv**:
"ORGANISATION_ID","NAME","ISOA3CODE","DESCRIPTION","BRANCH","STATUS","PARENT_ID"
"0","EC","EEC","European Commission","NULL","E",**"NULL"**

**Maven warning**:
Could not snapshot table 'organisation_t' to get the missing column type information

During **Docker startup**:
postgres> 2020-01-21 08:49:59.152 UTC [180] ERROR:  invalid input syntax for integer: "" at character 161
postgres> 2020-01-21 08:49:59.152 UTC [180] STATEMENT:  INSERT INTO ORGANISATION_T (ORGANISATION_ID, NAME, ISOA3CODE, DESCRIPTION, BRANCH, STATUS, PARENT_ID) VALUES ('0', 'EC', 'EEC', 'European Commission', '', 'E', **''**), ...

### CODE REVIEW

**Review by peerik — COMMENTED** [review]
Our build will break when changelogs that already have been executed are modified. Can we fix this without modifying the old ones?

**Comment by psjobergprivat** [comment]
The checksum of the changesets are actually not affected by this change (I have verified that it doesn't). But for example changing the name of the file to be imported does affect the checksum, so they must have been quite specific what is part of checksum and what is not.

**Comment by peerik** [comment]
Ok, strange! I will never understand liquibase.. :p

**Review by peerik — APPROVED** [review]

**Comment by psjobergprivat** [comment]
:D They seem to have a thought but the "definition" is quite fluffy... http://www.liquibase.org/2009/03/what-effects-changeset-checksums.html

**Pull request merged**
