### PR TITLE
Including dependency of Audit model

### PR DESCRIPTION
**Pull request by hfpmartins**

### CODE REVIEW

**Comment by hfpmartins** [comment]
test me

**Comment by gregoryrinaldi** [comment]
test me

**Comment by gregoryrinaldi** [comment]
test me

**Comment by gregoryrinaldi** [comment]
test me

**Comment by peerik** [comment]
test me

**Comment by ebrygg** [comment]
test me

**Review by gregoryrinaldi — APPROVED** [review]

**Pull request merged**
